# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yoimhere.github.io" # the base hostname & protocol for your site 

# User settings
username: OneByte
user_description: iOS Developer At WiFiTech
user_title: iOS Developer
email: yo_imhere@163.com
twitter_username: OneByte
github_username:  OneByte
gplus_username:  OneByte
disqus_username: OneByte

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 首页
    url: /
  - title: 系列
    url: /series
  - title: Tags
    url: /文章
  - title: 关于我
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
